- Quote-site/index.html
- Quote-site/quotes.js
- Quote-site/style.css
Quote Site. Give a new Quote on click.
> commited my quote site

- README.md
This Pull Request updates the README.md file with editing, concise English and lesser grammatical errors, making it more readable.
> Update README.md with more concise and clear language.

- Gradient-Generator/style.css/index.html
- Gradient-Generator/style.css/script.js
- Gradient-Generator/style.css/style.css
Hi, the code is ready. I made a gradient generator website, and I'm sending you the pull request.
> GRADIENT GENERATOR

- .replit
- portfolio/index.html
- portfolio/main.js
- portfolio/style.css
- replit.nix
Hi I have completed the code . I am sending the pull request
> Software Portfolio

- Glassomorphism/index.html
- Glassomorphism/style.css
Hey @Diptenusarkar, I'm sending the pull request. Please accept it. Thank you ❤️
> Glass Like Effect - Glassomorphism

- SECURITY.md
Added security procedures and steps.
> Created SECURITY.MD file

- Website Under construction/index.html
Another thing to point out is that I don't really understand what this line is doing. I'm assuming it's to link to a beta version of the website, but in that case, what's the point of this page?
> Fix awkward grammar issue

- NightMode/index.html
@Diptenusarkar Kindly look through my night mode feature and merge it as **hacktoberfest-accepted**. I hope you like it.
It also has the feature to retain the current theme **eve after refresh**.
> Night mode Toggler template

- ApprovalTemplate/index.html
- ApprovalTemplate/script.js
- ApprovalTemplate/style.css
@Diptenusarkar I have added approval rating template for websites .
Kindly look into it.
> Approval template for websites

- BOOKING TEMPLATE/index.html
- BOOKING TEMPLATE/style.css
WEB PAGE ADDED .
#57 
THANK YOU !
> HACKTOBERFEST-2022

- StickyNavbar/index.html
- StickyNavbar/style.css
desktop view
mobile view 
pls merge it
> sticky navbar is mobile responsive

- App Landing/style/main.css
Updated, html font-family to Montserrat.
> resolved issue #60

- 404 Page V2/404.html
- 404 Page V2/index.html
Added a new 404 Page for fans of Pokemon so maybe it makes someones day.
> New 404 Page.

- Login Page/loginkartik.html
newly modern style login template
> mynewloginpage

- Restaraunt Website/app.js
- Restaraunt Website/details.json
- Restaraunt Website/fonts.txt
- Restaraunt Website/index.html
- Restaraunt Website/style.css
New Website in collaboration with @DYNAMICMORTAL. Please merge the pull request.
> Restaraunt Website

- portfolio/style.css
> added transformation to 360 degrees to social icons when hovered

- Mansory Layout/index.html
- Mansory Layout/style.css
Here is the HTML and CSS Files for this project.
> Added the Mansory Layout Project #94

- Travel Blog/index.html
- Travel Blog/style/dsky/main.css
-form design improved 
-cards design improved with hover and shadow effect
-footer design change
> form & cards design improved in Travel blog

- contributing.md
Hi 
I have added the contributing.md file for this repo as a part of the hacktober fest 
Please accept the pull request
> Contributing.md file

- Payment-Gateway -template/README.md
- Payment-Gateway -template/payment.css
- Payment-Gateway -template/payment_form.html
This is a Payment form gateway. I have created this using HTML and CSS. In this form a user can input his/her details like name, gender , address , email and payment details like card no card type and CVV.
> This is a Payment form template.

- Responsive Navigation Bar using Bootstrap/index.html
Issue #89 
Adding Responsive Navbar Template by only using Bootstrap.
> Adding Responsive Navbar Template

- Grid Layout Templates/Grid Layout using bootstrap/grid1.html
- Grid Layout Templates/Grid Layout using bootstrap/grid2.html
- Grid Layout Templates/Grid Layout using bootstrap/index.html
- Grid Layout Templates/Grid Layout using simple CSS/index.html
- Grid Layout Templates/Grid Layout using simple CSS/styles.css
issue #90 
Adding Grid Layout Templates by using
-- only simple CSS
-- only Bootstrap
> Adding Grid Layout Templates

- CSS CARD HOVERING EFFECT/index.css
- CSS CARD HOVERING EFFECT/index.html
- Tribute Page Template/index.css
- Tribute Page Template/index.html
@Diptenusarkar I contributed  a CSS card hovering effect and a Tribute page template which I will  like you to check out 
Check the attached Screenshots
,
> Add CSS card hovering effect with a TRIBUTE PAGE TEMPLATE

- Interactive Tabs/css/style.css
- Interactive Tabs/index.html
An Interactive Tabs created in HTML and CSS only.
> Adding Interactive Tabs #106

- Theme Clock/index.html
- Theme Clock/script.js
- Theme Clock/style.css
Clock Added
issue[#97 ]
This can be use by anyone one to use in their project or take inspiration.
> theme clock

- Price Template/index.html
- Price Template/styles.css
issue #137
Adding price template using html and css
> Adding Price Template

- Payment Form/payment_form.html
- Payment Form/styles.css
issue #138
Adding Payment form Template using html and css.
Also add the label of hacktoberfest-accepted to it.
> Adding Payment Form Template

- 404_NotFound Page/404.css
- 404_NotFound Page/404.js
Hi I have added a 404 page, issue #134. It is made using react and styled majorly using css. I request you to merge this PR.
> Added a 404_NotFound page

- 404 Error Pages v4/Error1.html
Anchor tag added with hover effect..
> Added the anchor tag

- Login Page Template/index.html
- Login Page Template/style.css
Added a Login Page Template using HTML and CSS.
> Added a Login Page Template

- Form Wave Project/index.html
- Form Wave Project/script.js
- Form Wave Project/style.css
- A Form Wave using HTML,CSS,JS
- Click on text area to see the effect.
> Added Form wave Project

- Microsoft-clone/app.js
- Microsoft-clone/index.html
- Microsoft-clone/style.css
Added microsoft-clone with the help of html and css
> added Microsoft-clone

- css and java clock/index.html
>It is basically a clock which ensures you what time it is.
>It is a application made using css and javascript.
> Adding a clock

- CSS Cards Template/index.html
- CSS Cards Template/styles.css
issue #114
Adding CSS Cards Template with hover effects
> Adding CSS Cards Template

- videoplayer/index.html
- videoplayer/scripts.js
- videoplayer/style.css
>This is video Player application.
>Made using html , css, javascript.
> Adding video player

- sign up form/signup.html
> Hover effect on btn added of signup form

- Sidebar and Navbar Mobile/assets/css/style.css
- Sidebar and Navbar Mobile/assets/sidebar/sidebars.js
- Sidebar and Navbar Mobile/index.html
Signed-off-by: Chaitanya K <kchatsemo@gmail.com>
> Sidebar and Navbar added

- README.md
- translations/README.es.md
- translations/README.pt-br.md
I started the translation of some files.
After you approve my PR,  I will understand that make sense my contribution and then, keep writing something in your code.
> Paulpessoa readme translation

- Admin Dashboard/index.html
> fixes the issue of css

- Bank Account/index.css
- Bank Account/index.html
- Bank Account/index.js
added html , css, javascript file 
function of bank account
> added template for bank acccount

- ROADMAP/roadmap.css
- ROADMAP/roadmap.html
added some styles to roadmap.css
> added styles

- calculator/index.html
- calculator/index.js
- calculator/style.css
fixes #333 
added calculator template page
> added calculator template page

- Microsoft-clone/app.js
- Microsoft-clone/index.html
- Microsoft-clone/style.css
added a textbox input to appear when clicked on the search icon
> input text

- flappy bird/flappybird.html
- flappy bird/nbproject/project.properties
- flappy bird/nbproject/project.xml
added flappy bird game template
please add me as assignee and add hacktoberfest and hacktoberfest-accepted label
please merge this pr
thank you.
> flappy bird [hacktoberfest]

- LoadingAnimationButtonTemplate/index.html
- LoadingAnimationButtonTemplate/index.js
- LoadingAnimationButtonTemplate/style.css
Closes #351 ,
Please let me know if there is any issues
Please assign this to hacktober fest 
I would to slove if there is any issues 
samples 
Onclick each button has  the different animations 
video link is here 
https://drive.google.com/file/d/1K6FF2wxF7SCL_ZBGzM75bnu4fNJraZXe/view?usp=sharing
> added Loading Animation Button Template #351

- css and java clock/index.html
make the hands of clock differential, so that it will be practically possible to know the time from clock
> change the front-end #hacktoberfest

- mole game/index.html
- mole game/style.css
>  start btn position and styled well in mole game

- Node Express Template/.gitignore
- Node Express Template/controllers/controllers.js
- Node Express Template/index.js
- Node Express Template/package-lock.json
- Node Express Template/package.json
- Node Express Template/routes/routes.js
#360 
This is the template of node express server for quick start to making server
> node express template added

- Simple todo/index.html
- Simple todo/script.js
- Simple todo/style.css
Current outcome after adding dark mode is:
> dark mode added

- Lookup_task/.gitignore
- Lookup_task/Dockerfile
- Lookup_task/README.md
- Lookup_task/app.js
- Lookup_task/graphql/index.js
- Lookup_task/graphql/resolver/index.js
- Lookup_task/graphql/resolver/mutations/todos/updateTodo.js
- Lookup_task/graphql/resolver/queries/Doctor.js
- Lookup_task/graphql/resolver/queries/Todos.js
- Lookup_task/graphql/types/doctorsSchema/doctors.graphql
- Lookup_task/graphql/types/index.js
- Lookup_task/graphql/types/todos/todosData.graphql
- Lookup_task/package-lock.json
- Lookup_task/package.json
- Lookup_task/route/Patient.js
- Lookup_task/route/Slots.js
- Lookup_task/schema/doctors.js
- Lookup_task/schema/patient.js
- Lookup_task/schema/slots.js
- Lookup_task/schema/todo.js
@Diptenusarkar 
Node js and Graphql Backend Boilerplate Also Example of Query and mutation with docker
- #367
> feat:node-gql-backend issue # 367

- FeedbackPage/feedback.html
> Feedback Page Added

- ApprovalTemplate/index.html
- ApprovalTemplate/script.js
- ApprovalTemplate/style.css
made the code more user-friendly by adding a thank you message with a heading, displaying the selected feedback, and providing a personalized message indicating that the feedback will be used to enhance customer support services. The selected rating is now updated when the user clicks on a rating. Additionally, the code now handles clicks on both the rating icons and their corresponding text labels.
> user friendly modifications

- BackgroundAnimations/index.html
- BackgroundAnimations/index.js
- BackgroundAnimations/page2.html
- BackgroundAnimations/page3.html
- BackgroundAnimations/page4.html
- BackgroundAnimations/styles/page2css.css
- BackgroundAnimations/styles/page3.css
- BackgroundAnimations/styles/page4.css
- BackgroundAnimations/styles/style.css
please assign this under hack october fest 
Closes #383 
please let me know if there is any issues in it 
Page  4  sample
Page 3 Sample 
Page 2 Sample 
Page 1 Sample
>  Background animation added [October Hack Fest]

- Portfolio day-night toggle/index.html
- Portfolio day-night toggle/main.css
- portfolio/index.html
I changed the copyright of two files and made them dynamic which seems pretty now so please merge these changes under hactoberfest.
> Copyright changes

- ButtonTemplates/AnimatedLikeButton/app.css
- ButtonTemplates/AnimatedLikeButton/index.html
- ButtonTemplates/ArrowKeyButtons/app.css
- ButtonTemplates/ArrowKeyButtons/index.html
- ButtonTemplates/CyberpunkButton/app.css
- ButtonTemplates/CyberpunkButton/index.html
- ButtonTemplates/RainbowButtons/app.css
- ButtonTemplates/RainbowButtons/index.html
Added Rainbow Gradient Button and Arrow Buttons
> This fixes #404 

- Language Translator/index.html
- Language Translator/style.css
Please add my contribution for Hactoberfest.
> AddtheLanguaueTranslator

- CSS Cards Template/index.html
- CSS Cards Template/styles.css
- FeedbackPage/feedback.html
changed heading names as 01,02,03 and apply background color
> heading and bg clr change
